x-common-vars: &ros2-vars
  stdin_open: true
  tty: true
  privileged: true
  stop_grace_period: 1s
  restart: no
  network_mode: host
  working_dir: /home/user/localization-ws
  environment:
    - DISPLAY=${DISPLAY}
    # Set ros2 environment variables.
    # References:
    # - https://docs.ros.org/en/humble/Concepts/Intermediate/About-Domain-ID.html
    # - https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROS_WS=/home/user/localization-ws
  volumes:
    # Mount local timezone into container. ( Readonly )
    # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    # Mount X11 server
    - /tmp/.X11-unix:/tmp/.X11-unix
    # Mount device
    - /dev:/dev
    # Mount workspace
    - ../core_algorithm:/home/user/localization-ws/src/core_algorithm

services:
  localization-devel:
    profiles: ['local-developing']
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: user
    image: localization2026
    container_name: localization-devel
    <<: *ros2-vars
    command: /bin/bash

  localization-run:
    profiles: ['onboard-running']
    image: localization2026
    container_name: localization-run
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash"
        # ros2 launch ${ROS2_LAUNCH_FILE}"

  # containers for comunicating with firmware
  ros-core:
    profiles: ['communication']
    image: osrf/ros:noetic-desktop-full
    container_name: ros-core
    command: "rosmaster --core"
    network_mode: host
    stop_grace_period: 1s
    healthcheck:
      # The healthcheck is required for ros1-bridge to wait until roscore is ready.
      test: /ros_entrypoint.sh bash -c "rostopic list || exit 1"
      interval: 3s
      timeout: 10s
      retries: 5

  ros1-bridge:
    profiles: ['communication']
    build:
      context: .
      target: release
    image: pomelo925/ttennis-humble:communication
    container_name: ros2-ros1-bridge-ws
    stop_grace_period: 1s
    depends_on:
      ros-core:
        # The healthcheck is required for ros1-bridge to wait until roscore is ready.
        condition: service_healthy
    command: ./start-bridge.sh
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: /
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Direct Rendering Infrastructure
      - /dev/dri:/dev/dri
      # Shared Memory
      - /dev/shm:/dev/shm
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp=value

  ros1:
    profiles: ['communication']
    image: jossiewang/eurobot2025-localization:rosserial-chassis
    container_name: ros1
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    stop_grace_period: 1s
    depends_on:
      ros-core:
        condition: service_healthy
    command: /bin/bash -c "
            source /opt/ros/noetic/setup.bash && 
            source ~/ws/devel/setup.bash &&
            roslaunch odometry odometry_comm.launch"